// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGitIcon(arg1) {
  return window['go']['main']['App']['AddGitIcon'](arg1);
}

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function ClearShadowFile(arg1) {
  return window['go']['main']['App']['ClearShadowFile'](arg1);
}

export function DeleteGitIcon(arg1) {
  return window['go']['main']['App']['DeleteGitIcon'](arg1);
}

export function FixGrammar(arg1) {
  return window['go']['main']['App']['FixGrammar'](arg1);
}

export function GenerateContent(arg1, arg2) {
  return window['go']['main']['App']['GenerateContent'](arg1, arg2);
}

export function GetAllPreferences() {
  return window['go']['main']['App']['GetAllPreferences']();
}

export function GetAppState(arg1) {
  return window['go']['main']['App']['GetAppState'](arg1);
}

export function GetDefaultProjectRoot() {
  return window['go']['main']['App']['GetDefaultProjectRoot']();
}

export function GetFileTree(arg1) {
  return window['go']['main']['App']['GetFileTree'](arg1);
}

export function GetGitIcons() {
  return window['go']['main']['App']['GetGitIcons']();
}

export function GetPreference(arg1) {
  return window['go']['main']['App']['GetPreference'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetShadowFile(arg1) {
  return window['go']['main']['App']['GetShadowFile'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HasCorruption() {
  return window['go']['main']['App']['HasCorruption']();
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function OpenBrowser(arg1) {
  return window['go']['main']['App']['OpenBrowser'](arg1);
}

export function OpenGitClient(arg1) {
  return window['go']['main']['App']['OpenGitClient'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function RestoreBackup() {
  return window['go']['main']['App']['RestoreBackup']();
}

export function SaveAppState(arg1, arg2) {
  return window['go']['main']['App']['SaveAppState'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SavePreference(arg1, arg2) {
  return window['go']['main']['App']['SavePreference'](arg1, arg2);
}

export function SaveShadowFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveShadowFile'](arg1, arg2, arg3);
}

export function SelectCssFile() {
  return window['go']['main']['App']['SelectCssFile']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectExecutable() {
  return window['go']['main']['App']['SelectExecutable']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectSaveFile() {
  return window['go']['main']['App']['SelectSaveFile']();
}

export function SelectSvgFile() {
  return window['go']['main']['App']['SelectSvgFile']();
}

export function UpdateProjectLastOpened(arg1) {
  return window['go']['main']['App']['UpdateProjectLastOpened'](arg1);
}
