// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FixGrammar(arg1:string):Promise<string>;

export function GenerateContent(arg1:string,arg2:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SelectFile():Promise<string>;

export function SelectSaveFile():Promise<string>;
