// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddGitIcon(arg1:string):Promise<string>;

export function AddProject(arg1:string):Promise<void>;

export function ClearShadowFile(arg1:string):Promise<void>;

export function DeleteGitIcon(arg1:string):Promise<void>;

export function FixGrammar(arg1:string):Promise<string>;

export function GenerateContent(arg1:string,arg2:string):Promise<string>;

export function GetAllPreferences():Promise<Record<string, any>>;

export function GetAppState(arg1:string):Promise<string>;

export function GetDefaultProjectRoot():Promise<string>;

export function GetFileTree(arg1:string):Promise<Array<main.FileNode>>;

export function GetGitIcons():Promise<Record<string, string>>;

export function GetPreference(arg1:string):Promise<any>;

export function GetProjects():Promise<Array<main.Project>>;

export function GetShadowFile(arg1:string):Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function HasCorruption():Promise<boolean>;

export function ListFiles(arg1:string):Promise<Array<string>>;

export function OpenBrowser(arg1:string):Promise<void>;

export function OpenGitClient(arg1:string):Promise<boolean>;

export function ReadFile(arg1:string):Promise<string>;

export function RemoveProject(arg1:string):Promise<void>;

export function RestoreBackup():Promise<void>;

export function SaveAppState(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SavePreference(arg1:string,arg2:any):Promise<void>;

export function SaveShadowFile(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SelectCssFile():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectExecutable():Promise<string>;

export function SelectFile():Promise<string>;

export function SelectSaveFile():Promise<string>;

export function SelectSvgFile():Promise<string>;

export function UpdateProjectLastOpened(arg1:string):Promise<void>;
